function createEnum(values) {
  return Object.freeze(Object.fromEntries(values.map((value) => [value, value])));
}

export const DomainProgressionState = createEnum([
  "FUTURE",
  "LOCKED",
  "AVAILABLE",
  "ACTIVE",
  "MASTERED",
  "CONSEQUENCE",
]);

export const DomainConditionState = createEnum([
  "STABLE",
  "STRAINED",
  "CORRUPTED",
  "RECOVERING",
]);

export const MasteryStatus = createEnum([
  "NOT_ELIGIBLE",
  "ELIGIBLE",
  "IN_REVIEW",
  "MASTERED",
]);

export const MissionStatus = createEnum([
  "HIDDEN",
  "LOCKED",
  "AVAILABLE",
  "ACTIVE",
  "COMPLETED",
  "FAILED",
  "ABANDONED",
  "EXPIRED",
]);

export const MissionType = createEnum([
  "INTRODUCTION",
  "ACTION",
  "CONSISTENCY",
  "MILESTONE",
  "REFLECTION",
  "CHALLENGE",
  "RESTORATION",
]);

export const MissionScope = createEnum([
  "DOMAIN",
  "LEVEL",
  "BOSS",
  "TRANSVERSAL",
  "RESTORATION",
]);

export const ObjectiveType = createEnum([
  "BOOLEAN",
  "COUNT",
  "STREAK",
  "THRESHOLD",
  "CHECKLIST",
  "EVIDENCE",
  "DECISION",
]);

export const EvidenceLevel = createEnum([
  "SELF_REPORTED",
  "SUPPORTED",
  "VERIFIED",
]);

export const MissionCriticality = createEnum([
  "OPTIONAL",
  "STANDARD",
  "CORE",
  "MASTERY",
]);

export const MissionPriority = createEnum([
  "LOW",
  "MEDIUM",
  "HIGH",
  "URGENT",
]);

export const MissionDifficulty = createEnum([
  "EASY",
  "STANDARD",
  "HARD",
  "ELITE",
]);

export const RetryPolicy = createEnum([
  "NO_RETRY",
  "IMMEDIATE",
  "AFTER_REVIEW",
  "NEXT_CYCLE",
]);

export const BossScope = createEnum([
  "LEVEL",
  "DOMAIN",
  "TRANSVERSAL",
]);

export const BossStatus = createEnum([
  "HIDDEN",
  "REVEALED",
  "CHALLENGE_AVAILABLE",
  "CHALLENGED",
  "DEFEATED",
]);

export const DomainTierStatus = createEnum(["ACTIVE", "MASTERED"]);
export const MilestoneStatus = createEnum(["LOCKED", "AVAILABLE", "COMPLETED"]);
export const ConditionSignalType = createEnum(["NEGATIVE", "POSITIVE", "RESTORATIVE"]);
export const ConditionSignalSeverity = createEnum(["LOW", "MEDIUM", "HIGH", "CRITICAL"]);
export const AffinityStrength = createEnum(["LOW", "MEDIUM", "HIGH"]);

export const CommandType = createEnum([
  "MAKE_DOMAIN_AVAILABLE",
  "ACTIVATE_DOMAIN",
  "SET_DOMAIN_CONDITION",
  "START_DOMAIN_RECOVERY",
  "REVEAL_MISSION",
  "MAKE_MISSION_AVAILABLE",
  "START_MISSION",
  "COMPLETE_MISSION",
  "FAIL_MISSION",
  "ABANDON_MISSION",
  "EXPIRE_MISSION",
  "UPDATE_OBJECTIVE",
  "SUBMIT_EVIDENCE",
  "EVALUATE_DOMAIN_MASTERY",
  "REQUEST_DOMAIN_MASTERY",
  "GRANT_DOMAIN_MASTERY",
  "REJECT_DOMAIN_MASTERY",
  "MAKE_MILESTONE_AVAILABLE",
  "COMPLETE_MILESTONE",
  "REVEAL_BOSS",
  "EVALUATE_BOSS_AVAILABILITY",
  "CHALLENGE_BOSS",
  "DEFEAT_BOSS",
  "RECORD_CONDITION_SIGNAL",
  "RESOLVE_CONDITION_SIGNAL",
  "EVALUATE_DOMAIN_CONDITION",
  "ACTIVATE_RESTORATION_MISSION",
  "COMPLETE_DOMAIN_RESTORATION",
  "ACTIVATE_AFFINITY",
  "DEACTIVATE_AFFINITY",
]);

export const EventType = createEnum([
  "DOMAIN_AVAILABLE",
  "DOMAIN_ACTIVATED",
  "DOMAIN_STRAINED",
  "DOMAIN_CORRUPTED",
  "DOMAIN_RECOVERY_STARTED",
  "DOMAIN_RESTORED",
  "DOMAIN_RECOVERY_INTERRUPTED",
  "MISSION_REVEALED",
  "MISSION_AVAILABLE",
  "MISSION_STARTED",
  "MISSION_COMPLETED",
  "MISSION_FAILED",
  "MISSION_ABANDONED",
  "MISSION_EXPIRED",
  "OBJECTIVE_UPDATED",
  "EVIDENCE_SUBMITTED",
  "MISSION_PROGRESS_UPDATED",
  "MISSION_REWARD_GRANTED",
  "XP_GRANTED",
  "DOMAIN_PROGRESS_UPDATED",
  "MASTERY_ELIGIBILITY_CHANGED",
  "MASTERY_REVIEW_REQUESTED",
  "MASTERY_GRANTED",
  "MASTERY_REVIEW_REJECTED",
  "DOMAIN_TIER_MASTERED",
  "DOMAIN_MASTERED",
  "MILESTONE_AVAILABLE",
  "MILESTONE_COMPLETED",
  "BOSS_REVEALED",
  "BOSS_CHALLENGE_AVAILABLE",
  "BOSS_CHALLENGED",
  "BOSS_DEFEATED",
  "WORLD_LEVEL_PROGRESS_UPDATED",
  "WORLD_LEVEL_COMPLETED",
  "CONDITION_SIGNAL_RECORDED",
  "CONDITION_SIGNAL_RESOLVED",
  "DOMAIN_CONDITION_EVALUATED",
  "RESTORATION_MISSION_AVAILABLE",
  "AFFINITY_ACTIVATED",
  "AFFINITY_DEACTIVATED",
  "LEGACY_CONTRIBUTION_RECORDED",
]);

export const EngineErrorCode = createEnum([
  "INVALID_COMMAND",
  "ENTITY_NOT_FOUND",
  "DOMAIN_NOT_FOUND",
  "MISSION_NOT_FOUND",
  "MISSION_INSTANCE_NOT_FOUND",
  "INVALID_TRANSITION",
  "DOMAIN_NOT_AVAILABLE",
  "MISSION_NOT_AVAILABLE",
  "MISSION_NOT_ACTIVE",
  "MISSION_ALREADY_CLOSED",
  "INVALID_PAYLOAD",
  "OBJECTIVE_NOT_FOUND",
  "INVALID_OBJECTIVE_VALUE",
  "EVIDENCE_REQUIRED",
  "INVALID_EVIDENCE",
  "MISSION_REQUIREMENTS_NOT_MET",
  "REWARD_ALREADY_GRANTED",
  "INVALID_REWARD",
  "INVALID_XP_TRANSACTION",
  "DOMAIN_TIER_NOT_FOUND",
  "MASTERY_NOT_ELIGIBLE",
  "MASTERY_NOT_IN_REVIEW",
  "MASTERY_ALREADY_GRANTED",
  "MASTERY_REQUIREMENTS_NOT_MET",
  "MASTERY_REJECTION_REASON_REQUIRED",
  "MILESTONE_NOT_FOUND",
  "MILESTONE_NOT_AVAILABLE",
  "MILESTONE_REQUIREMENTS_NOT_MET",
  "BOSS_NOT_FOUND",
  "BOSS_NOT_REVEALED",
  "BOSS_NOT_AVAILABLE",
  "BOSS_NOT_CHALLENGED",
  "BOSS_REQUIREMENTS_NOT_MET",
  "INVALID_REQUIREMENT_GROUP",
  "WORLD_LEVEL_NOT_FOUND",
  "CONDITION_SIGNAL_NOT_FOUND",
  "INVALID_CONDITION_SIGNAL",
  "CONDITION_SIGNAL_ALREADY_RESOLVED",
  "CONDITION_EVALUATION_NOT_APPLICABLE",
  "RESTORATION_NOT_AVAILABLE",
  "RESTORATION_REQUIREMENTS_NOT_MET",
  "RESTORATION_MISSION_NOT_FOUND",
  "AFFINITY_NOT_FOUND",
  "AFFINITY_ALREADY_ACTIVE",
  "AFFINITY_ALREADY_INACTIVE",
  "DUPLICATE_ACTIVE_AFFINITY",
  "INVALID_AFFINITY",
  "INVALID_CONTRIBUTION",
  "DUPLICATE_CONTRIBUTION",
  "LEGACY_DOMAIN_INVALID_STATE",
]);

export const GameEnums = Object.freeze({
  DomainProgressionState,
  DomainConditionState,
  MasteryStatus,
  MissionStatus,
  MissionType,
  MissionScope,
  ObjectiveType,
  EvidenceLevel,
  MissionCriticality,
  MissionPriority,
  MissionDifficulty,
  RetryPolicy,
  BossScope,
  BossStatus,
  DomainTierStatus,
  MilestoneStatus,
  ConditionSignalType,
  ConditionSignalSeverity,
  AffinityStrength,
  CommandType,
  EventType,
  EngineErrorCode,
});

export function isEnumValue(enumCatalog, value) {
  return Object.hasOwn(enumCatalog, value);
}
